apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - sealed-secret.yaml
namespace: default
images:
  - name: ghcr.io/codingric/moneyman/up-webhook
    newTag: 38d89d8