resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
namespace: default
generators:
  - secret-generator.yaml
images:
  - name: ghcr.io/codingric/moneyman/up-webhook
    newTag: ${GIT_SHA}
