apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:IZe8oJu4XIAyGgJq2CZxMLHDk6v/iWbW8dJwNJpL7djwJkpByf0iIvt/FS47U2WbApw2OJj4l9b5a3KFz833WUt2ITf7MakxxUvb/JucTOXoL1qZagXso0qp1RWhlXEBKB4GbHTub/3raDLU3fHbd+P50wKdt/47ddxCFK4Ml6k=,iv:IEIcSSd7pwWWC1tLX/27fJ1KfZm4qbcz1+RcrZIwt+U=,tag:yTFzPBtph4Nnj+2Y+TKtpA==,type:str]
kind: Secret
metadata:
    name: moneyman-up-webhook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-26T09:11:11Z"
    mac: ENC[AES256_GCM,data:G2UTG2eY3WOk+KN+AnmjtgoYGrY92LP5sTmlS2yZe6ClwxP3eHl7WQBmeQYOAXqB2GrzJNdU0Ebu/FbfqLPoWoGUtj8YOwpNAZs2a60HOjeeEwnk8MdF2RbEuagufDwnN6gYZq5bNhsCb21yu8746vzuinmPsgCtWxZMIxH4+U8=,iv:obK3xLxCCUSS0geKBhIXF0oGNJh+f/nFeYi46RdM3jM=,tag:tN+gKS+2tlec4I90Ln27Yw==,type:str]
    pgp:
        - created_at: "2022-02-26T09:11:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4JFS++jXvqcARAAwbCWKecmQ4D5CVuoJn2MgFy4L+6MJrGsRCFQQbT+bi07
            LIatqB4qXAj/uoMUN5q/i4PQWkZuC6sF+iLVZhW5XSJM/bxVOMAkuagKDU3nU72z
            y1rHXd+d/fIIJFPvKRQOmLwbuETAewzEjgbCxkKGTDwzAKKoYLS69Hw5auc2hZqy
            ArIjQbHdC+9sliQTBYFViHMOMYqXtyfvG2xpXcQZrpKqMI2KRBbMZSP33+3498Rn
            3S4b+GkmY8+XbUGVA/NcEQKocONQIXGpOg9JxixUZcaXI/eALZQrGEZka/uu1NLb
            jbkkgsqDifzNxVT47HVM71w9tvK69nT48VwZu0QuhDc5hkUs550Iib+qL8f/6/XF
            fR4SnwuBXQQs816dRxnsqW4tZYcgOSr+VjSAE7rimBOLQ8Hrnm7KlTvo/gxtcIhb
            wb5kKB7aKt8lyJGhicshWC5uCBIoBA5JbbeMoIabg0j+79dQNO6FWv8t/1U1CQrs
            5OR1VNO5eJbAoxjSvf3gJGFCWS8/K7D2vQc3tK9OXABxkw8CURZUsOyqc1+b0L6v
            LAJD7Ei72BmVVt2pw7fleuW5Q1GYQgAMLV9Wf6rV+lka09pu9mBhzqJsyc7XpKmS
            LuHeRmHjJat9DK1MRZg1FGWbeL3ITE24XHEp4DVT1AChOdoK1n+5zMHoLO7oyQDS
            XgFlEhU2aCckWNvXmONEllgnnmCTqMHh+17MyeVnTeJ9PGn2AZU4uiyvF0FQ7PTi
            CRDeqCpvj1uMXdhjs9aTHOSMT4Ur4+/C22GQtq+CSXbNELRqUeDpatDdw07WpG0=
            =EV7S
            -----END PGP MESSAGE-----
          fp: E28363850AC1B6496CD89D27BB025BCA2ACFACC6
    encrypted_regex: ^(users|data|stringData)$
    version: 3.7.1
