version: '3.7'
services:
  trivy:
    image: ghcr.io/aquasecurity/trivy:latest
    command: |
      -q image --exit-code 1 -s HIGH ghcr.io/codingric/moneyman-backend:latest

  checkov:
    image: bridgecrew/checkov:latest
    command: '-d /src'
    volumes:
      - .:/src
  # tests:
  #   image: golang:alpine
  #   working_dir: /app
  #   volumes:
  #     - ./src/notifier:/app
  #   entrypoint: |
  #     sh -c 'apk add gcc libc-dev && go mod download && go test -v -cover'
