apiVersion: batch/v1
kind: CronJob
metadata:
  name: moneyman-auditor
spec:
  schedule: "00 9,23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: auditor
              image: ghcr.io/codingric/moneyman/auditor:$(GIT_SHA)
              env:
                - name: TZ
                  value: "Australia/Melbourne"
              args:
                - "-a"
                - "/etc/auditor/age.key"
                - "--loglevel"
                - "debug"
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: "/etc/auditor/config.yaml"
                  name: config
                  readOnly: true
                  subPath: config.yaml
                - mountPath: "/etc/auditor/age.key"
                  name: age
                  readOnly: true
                  subPath: age.key
          volumes:
            - name: config
              configMap:
                name: auditor-config
            - name: age
              secret:
                secretName: moneyman-age-key
          restartPolicy: Never
