apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:fQlSl5owV4ZTcxPve2TWcoKpOSCHLq7t+QYKDTJXbY70liqPOUjWq+3DHVH5RQ4yWMEYsnUfo261TnmDZlDCJPTUPI2j3x7Z4WAlwioOX+7iAqN+FWT82PGKpfF2hbGRCaBlG4BMm0KU6YosXzeEuex3i4IMLSSF9zow8NPxfZxVLBSemKOscXG4pe0O7rqzGeZcpI9KafMYwq5JffWO5PKRx8ZUN590vosK7RffWNaNd//oBFlKJ5ZCNkgfoarAu21p6eBNReBPhtKXyS33GeBTLJIHZSdytZZbUBJigy3T0m25/kTAUrxa9wqnJEExLROKxmTTQgP0n8sGAXNXPAJ2N9bjGKKeJ5e4v+ueaKVSC4hSkf/48xkujkZm0zUcUj6Pr9KcKyn1A7C1kUQAZl/5mdcGtS1C1I2NCYTqEETxaXVgYTs9DQ6srfvf6U+TlNpkZY5O+q99za0B37SecwILfVmEUuu4N0WBbqWHitx+DGNOBJqROoVqNHU6QU+meaA/yiM2/ohqEdcdAZqDdLtSLhvPIgaS8PZh7/JxXX5suErqkznMQ1KVE9smIyvYYu7hEUEAE57MO9IX,iv:m+Dv/PCtMVWufbEa6DYu2IOblvEGtIU4yVBmbzWNhKU=,tag:efpcL5zGSgyqG1Shjwl97w==,type:str]
kind: Secret
metadata:
    name: moneyman-auditor
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-22T08:55:14Z"
    mac: ENC[AES256_GCM,data:h3aIcpYuq1aQwpcNHTxnq09nV/adtbnNTYxsqLv+owx3xLkHBdWt4G9H8SInb0IHKBXt+wjZidCRBb1M0dKpz+ZgVGogaltSP22xeq+DyrEvpiu+S2f7RHvax3dCKvJvGSN1ykdmmlA8e9XRu7V058FQ7bTJFr0qh+4XNBr9e40=,iv:o4xici144xDGh4UKOlrfubjBpAveNoPBOQlgAvovb+M=,tag:wOBjBUVyQNqdo34sN1zb3Q==,type:str]
    pgp:
        - created_at: "2022-02-22T08:55:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4JFS++jXvqcARAAzeLhykB/HJZsNKJ4Hl46zy4D5exCCxNpSYq5BgKYvuhE
            46hG86ZrYlWzeZVFn4tWT8t50SdXT1KFYyrrDnrMBCwGyTWNFCQkUV5iAHh5qgmA
            afDLukr1EAKcl4xDXbEH8kqTmR/Bq35GWNj/l4vbyD2lnxUcVqtJSs1/pNL3Thf7
            gBq/CbQWKgsHUqAaORzwypjMGYy7D/AhWuB0TkHwJNMtqhP8NQxlnQGnoeTzEhcS
            zz5QJi7nPS6z+/9+NqBau4iRGtfA33CQjc8kejt4R34IB8LLMMQbb6LtXio8IjTy
            RgT6EyDlS7qmZddDeciSIZ9aPE0ZzaTHnmdqHju8jK2KBmVu8dg4sujXENRPdVag
            YBb5uqOmVPdiQ8u4uQwiL4Y2u1bHinY0+5ra4lw0XY81oO9MjbMJBIWsRZrvJrV4
            L+XJw+8ulsweNp2YaGkVxlouSVymCn6VYFPaXWmOtFXEtQzzxOeJr1aUtD94WoYv
            QBOv1cqf1n9NCQmB7QDPvAHNn+n4Q79QGjCTvkcv7zAtsKqKo6dtl4dYcPK+QnRe
            CQCY/mCsHxx6mfn+C92I64qAbNY5RPIZemO9FtxrWpR1flHWvFI2cE10GNnRKNp4
            QrPT+IG1oOem+D3DY3kXZCZNx/94gqy8aTMFHZvjm1azTw0z/hFtbnZ+t+LdV13S
            XgEsE54kIw3ViuG0SNQVasJBEzrc2BNkJ81jz9IITppnHemiielUEL2gsWWQ2BVX
            CrFfURAWJgh0q9JrRAb/EKtFqitxlrSlpZwc86E1Ma8ABIbUwjnLaXQxomBXnsE=
            =yRq7
            -----END PGP MESSAGE-----
          fp: E28363850AC1B6496CD89D27BB025BCA2ACFACC6
    encrypted_regex: ^(users|data|stringData)$
    version: 3.7.1
