checks:
  - type: amount
    name: Gowrie Daycare
    expected: 994.86
    days: 1
    match: Gowrie
    rrule: FREQ=WEEKLY;INTERVAL=2;WKST=TH;DTSTART=20220714T000000Z
backend: http://moneyman-backend:8080/transactions
notify:
  sid: age:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bG9XdWhJS1BtRkVzRmV4RHpSZE4vRzY2TWFtNkNoV3BVSUxrRytwWUVZCmFTM3BkTVk5Vnk3em1DWDl3NVpseWkycXY0NnluMTdCUktNdlZKQXVkQmMKLS0tIDJFZjhFc3I5cnJVaXpieHFjSUtObnJnQ2NXdlhYU0U0Nms5WVo5ck5IMVkKRwVACBdVuCj1NCXwi4TknoS9CArc5rDvNWUJXYtJwbDlb3fqPjm+RmUAg/SA5GQDmM72hnWGwkdoB5+hwbWBrS9F
  token: age:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bVpITXEzYXR2N3dVN3FMZ1FuUDVWWWNXTjRWMDhmaVZUUS9INnBoWjBFCklDcldadW16RGFGYlhTUHE4OExMU1Qxb0JweTJIVlNCdGxrUS9TSk1UVTgKLS0tICt2MGtkNDFzUFBxaEJyU2JnU3BkWkx4dG9rZzZoMERORkpoMmRGb2FaZWcKS3mfA+A8QW/N6jhDrkio6d9n7tSKgVcIH/1N9iIxvP7RJBRms6Skv9SX8beEpBCNf5N5D79otlZSBZJfCYBzZg==
  mobiles:
    - +61432071731