apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auditor.yaml
namespace: default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: auditor-config
  files:
    - config.yaml

images:
  - name: ghcr.io/codingric/moneyman/auditor
    newTag: 68b82fb