resources:
  - auditor.yaml
namespace: default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: auditor-config
  files:
    - config.yaml
- name: kustomize-auditor-deployment
  envs:
  - deploy.env

vars:
- name: GIT_SHA
  objref:
    kind: ConfigMap
    name: kustomize-auditor-deployment
    apiVersion: v1
  fieldref:
    fieldpath: data.GIT_SHA

configurations:
- configuration.yaml