apiVersion: batch/v1
kind: CronJob
metadata:
  name: bigbills
spec:
  schedule: "00 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bigbills
              image: codingric/bigbills
              args:
                - "-c"
                - "/etc/bigbills/config.yaml"
                - "-v"
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: "/etc/bigbills"
                  name: bigbills
                  readOnly: true
          volumes:
            - name: bigbills
              secret:
                secretName: bigbills
          restartPolicy: Never
