apiVersion: batch/v1
kind: CronJob
metadata:
  name: moneyman-bigbills
spec:
  schedule: "00 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bigbills
              image: ghcr.io/codingric/moneyman/bigbills
              env:
                - name: TZ
                  value: "Australia/Melbourne"
              args:
                - "-c"
                - "/etc/bigbills/config.yaml"
                - "-v"
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: "/etc/bigbills/config.toml"
                  name: config
                  readOnly: true
                  subPath: config.toml
                - mountPath: "/etc/bigbills/age.key"
                  name: age
                  readOnly: true
                  subPath: age.key
          volumes:
            - name: config
              configMap:
                name: bigbills-config
            - name: age
              secret:
                secretName: moneyman-age-key
          restartPolicy: Never
