apiVersion: batch/v1
kind: CronJob
metadata:
  name: moneyman-bigbills
spec:
  schedule: "0 8-22/3 * * *"
  timeZone: "Australia/Melbourne"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bigbills
              image: ghcr.io/codingric/moneyman/bigbills
              env:
                - name: TZ
                  value: "Australia/Melbourne"
                - name: ASPECTO_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aspecto-key
                      key: key
              args:
                - "-c"
                - "/etc/bigbills/config.toml"
                - "-v"
                - "-a"
                - "/etc/bigbills/age.key"
                - "-s"
                - "/var/run/bigbills/store.db"
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: "/etc/bigbills/config.toml"
                  name: config
                  readOnly: true
                  subPath: config.toml
                - mountPath: "/etc/bigbills/age.key"
                  name: age
                  readOnly: true
                  subPath: age.key
                - name: skv
                  mountPath: /var/run/bigbills/
          volumes:
            - name: config
              configMap:
                name: bigbills-config
            - name: age
              secret:
                secretName: moneyman-age-key
            - name: skv
              persistentVolumeClaim:
                claimName: bigbills-skv
          restartPolicy: Never
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bigbills-skv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
