apiVersion: batch/v1
kind: CronJob
metadata:
  name: moneyman-bigbills
spec:
  schedule: "0 8-22/3 * * *"
  timeZone: "Australia/Melbourne"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bigbills
              image: ghcr.io/codingric/moneyman/bigbills
              env:
                - name: TZ
                  value: "Australia/Melbourne"
                - name: REDIS_ADDRESS
                  value: redis.default:6379                  
                - name: OTEL_GRPC_ENDPOINT
                  value: "collector.aspecto.io:4317"
                - name: OTEL_AUTH_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aspecto-key
                      key: key    
              args:
                - "-c"
                - "/etc/bigbills/config.toml"
                - "-v"
                - "-a"
                - "/etc/bigbills/age.key"
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: "/etc/bigbills/config.toml"
                  name: config
                  readOnly: true
                  subPath: config.toml
                - mountPath: "/etc/bigbills/age.key"
                  name: age
                  readOnly: true
                  subPath: age.key
          volumes:
            - name: config
              configMap:
                name: bigbills-config
            - name: age
              secret:
                secretName: moneyman-age-key
          restartPolicy: Never

