resources:
  - bigbills.yaml
namespace: default
images:
  - name: ghcr.io/codingric/moneyman/bigbills
    newTag: ${GIT_SHA}
configMapGenerator:
- name: bigbills-config
  files:
    - config.toml
  options:
    disableNameSuffixHash: true
