apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bigbills.yaml

namespace: default

configMapGenerator:
- files:
  - config.toml
  name: bigbills-config
  options:
    disableNameSuffixHash: true

images:
  - name: ghcr.io/codingric/moneyman/bigbills
    newTag: latest
