resources:
  - bigbills.yaml

namespace: default

configMapGenerator:
- name: bigbills-config
  files:
    - config.toml
  options:
    disableNameSuffixHash: true
- name: kustomize-deployment
  envs:
  - deploy.env

vars:
- name: GIT_SHA
  objref:
    kind: ConfigMap
    name: kustomize-deployment
    apiVersion: v1
  fieldref:
    fieldpath: data.GIT_SHA

configurations:
- configuration.yaml
