---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Money management lambdas to process transaction and other logic

Parameters:
  EventBusName:
    Type: String
    Default: moneyman-events

Resources:

  ClientSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "/moneyman/google/clientsecret"

  ProcessBigBills:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/ProcessBigBills
      FunctionName: ProcessBigBills
      Handler: lambda.handler
      Role: !GetAtt MoneymanLambdaRole.Arn
      Runtime: python3.8
      Timeout: 300
      MemorySize: 128
      # Environment:
      #   Variables:
      #     CLIENT_SECRET: !Ref ClientSecretJSON
      Layers:
        - !Ref GoogleLayer

  Twilio:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Twilio
      FunctionName: Twilio
      Handler: lambda.handler
      Runtime: python3.8
      Timeout: 20
      MemorySize: 128

  IncommingTransaction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/IncommingTransaction
      FunctionName: IncommingTransaction
      Handler: lambda.handler
      Role: !GetAtt MoneymanLambdaRole.Arn
      Runtime: python3.8
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          EVENTBUS_NAME: !Ref MoneyBus
          DYNAMOTABLE_NAME: !Ref TransactionArchive
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/IncommingTransaction'
            Method: post

  MoneyBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref EventBusName

  TransactionArchive:
    Type: AWS::DynamoDB::Table
    Properties:
      #TableName: TransactionArchive
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: When
          AttributeType: S
        - AttributeName: RequestID
          AttributeType: S
      KeySchema:
        - AttributeName: RequestID
          KeyType: HASH
        - AttributeName: When
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true


  GoogleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./src/GoogleLayer
      CompatibleRuntimes:
        - python3.8
      Description: Google API
      LayerName: GoogleLayer

  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "MondayBigBills"
      ScheduleExpression: "cron(0 15 ? * 1 *)"
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt ProcessBigBills.Arn
          Id: "MondayBigBills"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessBigBills
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"

  MoneymanLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: moneyman-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowLambdaToAssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CWLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                Effect: "Allow"
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
              - Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*
              - Action:
                  - "events:PutEvents"
                Effect: "Allow"
                Resource:
                  - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${EventBusName}
              - Action:
                  - "dynamodb:PutItem"
                Effect: "Allow"
                Resource:
                  - !GetAtt TransactionArchive.Arn
              - Action:
                  - "secretsmanager:GetSecretValue"
                Effect: "Allow"
                Resource:
                  - !Ref ClientSecret