---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Money management lambdas to process transaction and other logic

Resources:

  ProcessBigBills:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/ProcessBigBills
      FunctionName: ProcessBigBills
      Handler: lambda.handler
      Role: !GetAtt MoneymanLambdaRole.Arn
      Runtime: python3.8
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          SOMETHING: "{}"
      Layers:
        - !Ref GoogleLayer

  GoogleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./src/GoogleLayer
      CompatibleRuntimes:
        - python3.8
      Description: Google API
      LayerName: GoogleLayer

  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "MondayBigBills"
      ScheduleExpression: "cron(0 15 ? * 1 *)"
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt ProcessBigBills.Arn
          Id: "MondayBigBills"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessBigBills
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"

  MoneymanLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: moneyman-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowLambdaToAssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CWLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                Effect: "Allow"
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
              - Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*