webhook: http://moneyman-backend:8080/transactions
patterns:
  - '(?P<negative>spent) \$(?P<amount>\d{1,}\.\d{2}) at (?P<description>[^.]+)'
  - '(?P<negative>payment) of \$(?P<amount>\d{1,}\.\d{2}) to (?P<description>[^.]+)'
  - '(?P<negative> )\$(?P<amount>\d{1,}\.\d{2}) was moved between your ING accounts, (?P<description>[^.]+)'
  - '(?P<description>withdrawal) of(?P<negative> )\$(?P<amount>\d{1,}\.\d{2}) was made from your'
  - '\$(?P<amount>\d{1,}\.\d{2}) (?P<description>deposit) has been made into your'
  - 'that (?P<description>.*) deposited \$(?P<amount>\d{1,}\.\d{2}) into your'
  - '\$(?P<amount>\d{1,}.\d{2}) has been (?P<description>deposited into your \w+ from your \w+)'
logging:
  path: /store