resources:
  - mailparser.yaml
namespace: default
images:
  - name: ghcr.io/codingric/moneyman/mailparser
    newTag: 38d89d8

configMapGenerator:
- name: moneyman-mailparser
  files:
    - config.yaml
