---
apiVersion: v1
kind: Service
metadata:
  name: moneyman-mailparser
  labels:
    app: moneyman-mailparser
spec:
  type: ClusterIP
  ports:
    - name: moneyman-mailparser
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: moneyman-mailparser
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moneyman-mailparser
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/client-max-body-size: "0"
    nginx.org/proxy-connect-timeout: 600s
    nginx.org/proxy-read-timeout: 600s
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: moneyman.k3s.salinas.id.au
      http:
        paths:
          - path: /mail(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: moneyman-mailparser
                port:
                  number: 8081
  tls:
    - hosts:
        - moneyman.k3s.salinas.id.au
      secretName: moneyman-mailparser-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneyman-mailparser
  labels:
    app: moneyman-mailparser
spec:
  selector:
    matchLabels:
      app: moneyman-mailparser
  template:
    metadata:
      labels:
        app: moneyman-mailparser
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: moneyman-mailparser
          image: "ghcr.io/codingric/moneyman/mailparser"
          env:
            - name: TZ
              value: "Australia/Melbourne"
          imagePullPolicy: Always
          args:
            - "-v"
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/mailparser
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: moneyman-mailparser
