version: "3.2"
services:
  flask:
    image: registry.salinas.id.au/moneyman
    build: .
    ports:
    - "5000:5000"
    volumes:
    - "../moneyman/build/static:/app/static"
    - "../moneyman/dist:/app/dist"