name: Build docker image

on: [push]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Dockerfile scans
      #   run: docker-compose run checkov

      # - name: Run unit tests
      #   run: docker-compose run tests

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: codingric
          password: ${{ secrets.GHCR_PAT }}

      - name: Build docker image
        run: make package

      # - name: Static scans
      #   run: docker-compose run trivy
